baseUrl: 'https://synthvfes.jp/'
languageCode: 'ja-jp'
title: 'Synthesizer V Unofficial Festival 2023'
theme: 'sakura'
params:
  author: 'Nectarition'
  since: 2022
  event:
    logo: '/logo.svg'
    genre: ''
    name: 'Synthesizer V Unofficial Festival 2023'
    subTitle: 'Synthesize V 音楽投稿祭'
    date: '2023年2月4日〜6日'
    place: 'ニコニコ動画内'
    illustrator: ''
  TwitterScreenName: 'nct_synthvfes'
  GoogleAnalyticsMeasuringId: 'G-NJN40E6S69'

markup:
  defaultMarkdownHandler: 'goldmark'
  goldmark:
    renderer:
      unsafe: true
